name: Build
on:
  push:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: volta-cli/action@v4

      - name: Install dependencies
        run: |
          npm install

      - name: Run Build
        run: |
          npm run build

      - name: Check for changes
        run: |
          git status --porcelain | grep -q "dist/" && SHOULD_PUSH=1 || SHOULD_PUSH=0

          if [ $SHOULD_PUSH -eq 1 ]; then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git commit -am "Update dist folder" && git push
          fi
