name: Dependabot Build
on:
  push:
    branches:
      - dependabot/**

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: volta-cli/action@v4

      - name: Install dependencies
        run: |
          npm install

      - name: Run Build
        run: |
          npm run build

      - name: Push Changes
        run: |
          git config user.name dependabot[bot]
          git config user.email 49699333+dependabot[bot]@users.noreply.github.com
          git commit -am "Update dist folder" && git push
