# Tests this action failure by the application not being installed on the repository

name: Test Failure - repository - not installed

on:
  push:
  workflow_dispatch:

jobs:
  test_failure:
    runs-on: ubuntu-latest

    outputs:
      action_step_outcome: ${{ steps.use_action.outcome }}
      action_step_conclusion: ${{ steps.use_action.conclusion }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use action
        id: use_action
        continue-on-error: true
        uses: ./
        with:
          application_id: ${{ secrets.APPLICATION_ID_NOT_INSTALLED }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY_NOT_INSTALLED }}

      - name: Ensure Previous Step Failed
        if: steps.use_action.outcome != 'failure'
        run: exit 1
